//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foursquare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speakers
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Picture { get; set; }
        public string BioName { get; set; }
        public string BioTitle { get; set; }
        public string Bio { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public bool isDeleted { get; set; }
    }
}
