//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foursquare.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class foursquareconfEntities : DbContext
    {
        public foursquareconfEntities()
            : base("name=foursquareconfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Welcome> Welcome { get; set; }
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Hosts> Hosts { get; set; }
        public virtual DbSet<Venue> Venue { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<WelcomeTeam> WelcomeTeam { get; set; }
        public virtual DbSet<Speakers> Speakers { get; set; }
        public virtual DbSet<Moderators> Moderators { get; set; }
        public virtual DbSet<Program> Program { get; set; }
    }
}
